### ISSUE TITLE
Fix gilt sync workflow

### ISSUE THREAD

**Issue by joshmue** [SovereignCloudStack/k8s-template#1]
Example of failed run: https://github.com/SovereignCloudStack/k8s-template/runs/950072624

CC @berendt

**Comment by joshmue** [comment]
As it seems, this is the cause of the errors:

```
! [remote rejected] chore/sync-with-generics-repository -> chore/sync-with-generics-repository (refusing to allow a GitHub App to create or update workflow `.github/workflows/ci-test-workflow.yml` without `workflows` permission)
```

**Comment by tibeer** [comment]
@joshmue is this still relevant?

**Comment by joshmue** [comment]
Let's wait for the next run of https://github.com/SovereignCloudStack/k8s-harbor/actions/workflows/sync-with-generics-repository.yml . I just re-enabled the workflow there and there should be changes to be committed.

**Comment by joshmue** [comment]
Error cause is still the same. @tibeer Could you grant the `workflows` permission to the CI identity? IIRC you added some project administration automation to this Github organisation.

**Comment by tibeer** [comment]
@joshmue cannot unfortunately. Automation is not live yet.

**Comment by joshmue** [comment]
@garloff Could you do that manually, then?

**Comment by joshmue** [comment]
Obsolete, I guess.
